export default {
  id: 'freeze-focus-dance',
  engine: 'coach-timer',
  title: 'Freeze Focus Dance',
  splashEmoji: 'emoji:🕺',
  theme: { world: 'paper-garden', background: './assets/bg.jpg' },
  voice: {
    intro: 'Get ready to dance wild and freeze solid!',
    praise: 'Strong freeze! Your focus is growing.',
    cheer: 'You danced, froze, and focused like a champion!',
  },
  modes: [
    {
      id: 'classic',
      title: 'Dance and Freeze',
      type: 'signal',
      rounds: 6,
      cheer: 'Six super freezes! Your body listened fast!',
      endTitle: 'Freeze Champion',
      endArt: 'emoji:🧊',
      againLabel: 'DANCE AGAIN',
      states: [
        {
          id: 'dance',
          art: 'emoji:🕺',
          color: '#f08a24',
          sfx: 'pop',
          say: 'DANCE! Shake everything!',
          durSec: [5, 10],
        },
        {
          id: 'freeze',
          art: 'emoji:🧊',
          color: '#2d7dd2',
          sfx: 'boing',
          say: 'FREEZE! Solid as ice!',
          durSec: [3, 5],
        },
      ],
    },
    {
      id: 'focus',
      title: 'Freeze Missions',
      type: 'signal',
      rounds: 6,
      cheer: 'Your waiting body and noticing eyes worked together!',
      endTitle: 'Focus Freeze Champion',
      endArt: 'emoji:🔵',
      againLabel: 'MISSION AGAIN',
      states: [
        {
          id: 'dance',
          art: 'emoji:🕺',
          color: '#f08a24',
          sfx: 'pop',
          say: 'DANCE! Shake everything!',
          durSec: [5, 10],
        },
        {
          id: 'find-blue',
          art: 'emoji:🔵',
          color: '#2d7dd2',
          sfx: 'boing',
          say: 'FREEZE! Keep still AND look at something blue!',
          durSec: [3, 5],
        },
        {
          id: 'one-foot',
          art: 'emoji:🦶',
          color: '#58a945',
          sfx: 'boing',
          say: 'FREEZE! Balance on one foot!',
          durSec: [3, 5],
        },
        {
          id: 'silly-face',
          art: 'emoji:🤪',
          color: '#9b5de5',
          sfx: 'silly',
          say: 'FREEZE! Hold your silliest face!',
          durSec: [3, 5],
        },
        {
          id: 'quiet-breath',
          art: 'emoji:😮‍💨',
          color: '#14a08a',
          sfx: 'sparkle',
          say: 'FREEZE! Breathe quietly and feel your body slow down.',
          durSec: [3, 5],
        },
      ],
    },
  ],
};
