const specimen = (id, name, fact, factKey) => ({
  id,
  name,
  asset: `./assets/specimens/${id}.webp`,
  fact,
  factKey,
});

export default {
  id: 'local-nature-guide',
  engine: 'custom',
  title: 'Local Nature Guide',
  artDirection: 'Watercolor / Storybook',
  progressKey: 'qlobe:local-nature-guide:journal:v1',
  assets: {
    title: './assets/ui/title.webp',
    prompt: './assets/ui/prompt-plate.webp',
    button: './assets/ui/button-wide.webp',
    journalTab: './assets/ui/journal-tab.webp',
    journalSlot: './assets/ui/sticker-carrier.webp',
    discoveryGlow: './assets/ui/discovery-glow.webp',
    badge: './assets/ui/badge.webp',
    traceBrush: './assets/ui/trace-brush.webp',
  },
  guides: {
    welcome: './assets/characters/suri-welcome.webp',
    point: './assets/characters/suri-point.webp',
    listen: './assets/characters/suri-listen.webp',
    trace: './assets/characters/suri-trace.webp',
    journal: './assets/characters/suri-journal.webp',
    celebrate: './assets/characters/suri-celebrate.webp',
  },
  specimens: {
    pinecone: specimen('pinecone', 'Pinecone', 'Pinecones hold and protect the seeds of pine trees.', 'fact-pinecone'),
    'maple-leaf': specimen('maple-leaf', 'Maple leaf', 'A maple leaf has pointed lobes spreading out from one stem.', 'fact-maple-leaf'),
    'river-stone': specimen('river-stone', 'River stone', 'Moving water tumbles stones and slowly smooths their edges.', 'fact-river-stone'),
    chickadee: specimen('chickadee', 'Chickadee', 'A chickadee can sing its own name: chick-a-dee-dee-dee.', 'fact-chickadee'),
    robin: specimen('robin', 'Robin', 'Robins sing bright, whistled phrases from branches and lawns.', 'fact-robin'),
    woodpecker: specimen('woodpecker', 'Woodpecker', 'Woodpeckers drum on wood to send a message through the forest.', 'fact-woodpecker'),
    rabbit: specimen('rabbit', 'Rabbit', 'A rabbit usually leaves its long hind prints ahead of its smaller front prints.', 'fact-rabbit'),
    deer: specimen('deer', 'Deer', 'A deer track shows two pointed hoof marks, often shaped like a small heart.', 'fact-deer'),
    raccoon: specimen('raccoon', 'Raccoon', 'Raccoon tracks have five long toes that look a little like tiny hands.', 'fact-raccoon'),
  },
  forestPool: ['pinecone', 'maple-leaf', 'river-stone', 'acorn', 'fern', 'feather'],
  modes: [
    {
      id: 'forest',
      title: 'Forest Finds',
      subtitle: 'Look closely',
      card: './assets/ui/mode-forest.webp',
      scene: './assets/backgrounds/forest-clearing.webp',
      guide: 'point',
      introKey: 'forest-intro',
      completeKey: 'forest-complete',
      rounds: [
        { id: 'pinecone', promptKey: 'find-pinecone' },
        { id: 'maple-leaf', promptKey: 'find-maple-leaf' },
        { id: 'river-stone', promptKey: 'find-river-stone' },
      ],
    },
    {
      id: 'birds',
      title: 'Bird Listening',
      subtitle: 'Use your ears',
      card: './assets/ui/mode-birds.webp',
      scene: './assets/backgrounds/bird-meadow.webp',
      guide: 'listen',
      introKey: 'birds-intro',
      completeKey: 'birds-complete',
      rounds: [
        { id: 'chickadee', promptKey: 'listen-chickadee' },
        { id: 'robin', promptKey: 'listen-robin' },
        { id: 'woodpecker', promptKey: 'listen-woodpecker' },
      ],
    },
    {
      id: 'tracks',
      title: 'Track Finder',
      subtitle: 'Follow the trail',
      card: './assets/ui/mode-tracks.webp',
      scene: './assets/backgrounds/muddy-trail.webp',
      guide: 'trace',
      introKey: 'tracks-intro',
      completeKey: 'tracks-complete',
      rounds: [
        { id: 'rabbit', promptKey: 'trace-rabbit', checkpoints: [[0.55, 0.9], [0.47, 0.77], [0.55, 0.64], [0.44, 0.5], [0.54, 0.36], [0.47, 0.22], [0.54, 0.08]] },
        { id: 'deer', promptKey: 'trace-deer', checkpoints: [[0.58, 0.9], [0.49, 0.77], [0.55, 0.64], [0.43, 0.5], [0.54, 0.36], [0.47, 0.22], [0.54, 0.08]] },
        { id: 'raccoon', promptKey: 'trace-raccoon', checkpoints: [[0.57, 0.9], [0.48, 0.77], [0.56, 0.64], [0.44, 0.5], [0.54, 0.36], [0.47, 0.22], [0.54, 0.08]] },
      ],
    },
  ],
  voice: {
    welcome: 'Welcome, Nature Guide! Pick a trail and let us look closely.',
    'forest-intro': 'Forest Finds! Look carefully and tap the treasure I name.',
    'find-pinecone': 'Can you find the pinecone?',
    'find-maple-leaf': 'Can you find the maple leaf?',
    'find-river-stone': 'Can you find the smooth river stone?',
    'birds-intro': 'Bird Listening! Hear the call, then choose the bird who made it.',
    'listen-chickadee': 'Listen closely. Which bird made that call?',
    'listen-robin': 'A new forest song! Which bird made that call?',
    'listen-woodpecker': 'Listen for the forest drummer. Which bird made that sound?',
    'tracks-intro': 'Track Finder! Trace each trail, then choose the animal who left it.',
    'trace-rabbit': 'Start at the glowing print and trace the rabbit trail.',
    'trace-deer': 'Start at the glowing print and trace the deer trail.',
    'trace-raccoon': 'Start at the glowing print and trace the raccoon trail.',
    'trace-ready': 'Trail complete! Who left these tracks?',
    praise: 'Wonderful noticing! Into your nature journal it goes.',
    wrong: 'Good looking. Try another one.',
    'trace-again': 'Stay close to the trail and keep going.',
    'forest-complete': 'Forest Finds complete! Your journal has three new treasures.',
    'birds-complete': 'Bird Listening complete! Your journal is full of forest songs.',
    'tracks-complete': 'Track Finder complete! You followed every clue.',
    'journal-intro': 'Here is your nature journal. Tap any discovery to hear its story.',
    'journal-empty': 'Your journal is waiting for discoveries. Choose a trail to begin.',
    'all-complete': 'You found every discovery! You are an official Local Nature Guide.',
    'fact-pinecone': 'Pinecones hold and protect the seeds of pine trees.',
    'fact-maple-leaf': 'A maple leaf has pointed lobes spreading out from one stem.',
    'fact-river-stone': 'Moving water tumbles stones and slowly smooths their edges.',
    'fact-chickadee': 'A chickadee can sing its own name: chick-a-dee-dee-dee.',
    'fact-robin': 'Robins sing bright, whistled phrases from branches and lawns.',
    'fact-woodpecker': 'Woodpeckers drum on wood to send a message through the forest.',
    'fact-rabbit': 'A rabbit usually leaves its long hind prints ahead of its smaller front prints.',
    'fact-deer': 'A deer track shows two pointed hoof marks, often shaped like a small heart.',
    'fact-raccoon': 'Raccoon tracks have five long toes that look a little like tiny hands.',
  },
};
