// lines.js — the complete spoken script (generated from the voice batch
// table so recordings and fallbacks can never drift). Keys match clips.

export const DEFAULT_LINES = {
  "intro": "Hi, I'm Ravi! Let's play Feelings Charades. You can act out big feelings, or guess them. Pick a game!",
  "mode-act": "Act It Out! Pick a feeling card, watch a friend show it, then act it out with your whole body.",
  "mode-guess": "Guess the Feeling! Listen to the body clues, then tap the feeling face.",
  "grid-prompt": "Tap a feeling card.",
  "your-turn": "Now it's YOUR turn!",
  "done-early": "Beautiful acting!",
  "all-stars": "You acted out every feeling! You are a feelings expert. Big feelings, small feelings, you know what to do.",
  "cheer-guess": "Feelings charades finished! You know your feelings!",
  "nudge-guess": "That face does not match yet. Listen to the body clues again.",
  "try-another": "Try another feeling!",
  "happy-label": "Happy!",
  "happy-demo": "Maya feels happy! Her eyes are bright, she is smiling big, and she bounces on her toes.",
  "happy-invite": "Show me YOUR happy! Smile big and bounce!",
  "happy-enc1": "Yes! Look at that smile!",
  "happy-enc2": "Bounce, bounce, bounce!",
  "happy-affirm": "Well done! That looked happy!",
  "happy-learn": "When you feel happy, share your smile. It spreads!",
  "proud-label": "Proud!",
  "proud-demo": "Maya feels proud! She worked hard and did it. She stands tall, hands on her hips, chin up, big smile.",
  "proud-invite": "Show me YOUR proud! Stand tall and smile!",
  "proud-enc1": "So tall! Chin up!",
  "proud-enc2": "Hands on hips. Ta-da!",
  "proud-affirm": "Well done! That looked proud!",
  "proud-learn": "When you feel proud, stand tall and say: I did it!",
  "frustrated-label": "Frustrated!",
  "frustrated-demo": "Leo feels frustrated! The puzzle piece will not fit. His arms are crossed, his eyebrows squeeze together, and he stomps one foot. Hmph!",
  "frustrated-invite": "Show me YOUR frustrated! Cross your arms and stomp. Hmph!",
  "frustrated-enc1": "Big stomp! Squeeze those eyebrows!",
  "frustrated-enc2": "One more stomp!",
  "frustrated-affirm": "Wonderful acting! That looked frustrated!",
  "frustrated-learn": "It's okay to feel frustrated. Let's learn a trick for it.",
  "frustrated-cope-intro": "When frustration feels too big, we can breathe it smaller. Let's take three slow breaths together.",
  "frustrated-breathe-in": "Breathe in... slowly...",
  "frustrated-hold": "Hold it...",
  "frustrated-breathe-out": "And breathe out... all the way...",
  "frustrated-cope-done": "Feel that? Your body is calm again. You can always breathe a big feeling smaller.",
  "excited-label": "Excited!",
  "excited-demo": "Leo feels excited! Something amazing is about to happen. His hands wave fast, his feet dance, and his eyes are wide!",
  "excited-invite": "Show me YOUR excited! Wave your hands and dance!",
  "excited-enc1": "Faster, faster!",
  "excited-enc2": "Wiggle those excited feet!",
  "excited-affirm": "Well done! That looked excited!",
  "excited-learn": "When you feel excited, you can jump, dance, and tell a friend why!",
  "sad-label": "Sad!",
  "sad-demo": "Nia feels sad. She misses her toy. Her shoulders are low, her head hangs down, and her voice is tiny.",
  "sad-invite": "Show me YOUR sad. Let your shoulders sink down low.",
  "sad-enc1": "Slow and droopy...",
  "sad-enc2": "A tiny quiet sigh...",
  "sad-affirm": "Beautiful acting. That looked sad.",
  "sad-learn": "It's okay to feel sad. Sad needs a helper.",
  "sad-cope-intro": "When you feel sad, a hug helps. Think of your hug person. Who would you ask?",
  "sad-cope-action": "Now give yourself a big squeeze hug. Squeeze... and let go.",
  "sad-cope-done": "Hugs help sad feelings get softer. You can always ask for one.",
  "calm-label": "Calm!",
  "calm-demo": "Nia feels calm. Her body is still like quiet water. She breathes in slowly... and out slowly.",
  "calm-invite": "Show me YOUR calm. Be still, and breathe slow.",
  "calm-enc1": "So still... so quiet...",
  "calm-enc2": "One more slow breath...",
  "calm-affirm": "Beautiful. That looked calm.",
  "calm-learn": "Calm is a superpower. You can find it with one slow breath.",
  "worried-label": "Worried!",
  "worried-demo": "Sam feels worried. What if he cannot find his shoe? His tummy feels jumpy, his eyebrows squeeze, and his hands twist together.",
  "worried-invite": "Show me YOUR worried. Squeeze your eyebrows, twist your hands.",
  "worried-enc1": "Oh no, where is that shoe?",
  "worried-enc2": "Jumpy tummy face!",
  "worried-affirm": "Great acting! That looked worried!",
  "worried-learn": "It's okay to feel worried. Worries get smaller when we share them.",
  "worried-cope-intro": "When you feel worried, talk to someone you trust. Let's practice. Say it with me:",
  "worried-cope-action": "I feel worried. Can you help me?",
  "worried-cope-done": "That's it! Grown-ups love to help with worries. You never have to hold one alone.",
  "shy-label": "Shy!",
  "shy-demo": "Sam feels shy. There are new friends at the park. He peeks out, his chin tucks down, and he gives a tiny little wave.",
  "shy-invite": "Show me YOUR shy. Tuck your chin and do a tiny wave.",
  "shy-enc1": "A little peek...",
  "shy-enc2": "The tiniest wave in the world...",
  "shy-affirm": "Well done! That looked shy!",
  "shy-learn": "Shy is okay. A tiny wave is a brave hello.",
  "guess-frustrated": "I am stomping my feet. My arms are crossed. Hmph! What feeling is this?",
  "guess-happy": "My eyes are bright. I am smiling and bouncing. Hooray! What feeling is this?",
  "guess-sad": "My shoulders are low. My voice is tiny. I miss my toy. What feeling is this?",
  "guess-worried": "My tummy feels jumpy. My eyebrows are squeezed. What if I cannot find it? What feeling is this?",
  "guess-calm": "My body is still. I breathe in slowly, and out slowly. What feeling is this?",
  "guess-proud": "I worked hard and did it. My chest feels tall. Ta-da! What feeling is this?",
  "yum-1": "You named the feeling.",
  "yum-2": "Good listening to the body clues.",
  "yum-3": "Yes, that face matches the feeling.",
  "yum-4": "Now show that feeling big, then let it soften."
};
