export default {
  id: 'balance-beam-trail',
  engine: 'coach-timer',
  title: 'Balance Beam Trail',
  splashEmoji: 'emoji:🤸',
  theme: { world: 'field-journal', background: './assets/bg.jpg' },
  voice: {
    intro: 'Find your focus and take it slowly. Wobbles mean your balance is learning!',
    praise: 'Nice recovery. Calm and steady!',
    cheer: 'Superstar balance! Every wobble helped you learn!',
  },
  modes: [
    {
      id: 'floor',
      title: 'Tape Trail',
      type: 'steps',
      praise: 'Nice recovery. Calm and steady!',
      cheer: 'Superstar balance! You finished the tape trail!',
      endTitle: 'Tape Trail',
      endArt: 'emoji:🌟',
      againLabel: 'AGAIN',
      doneLabel: 'DONE',
      steps: [
        { art: 'emoji:📏', say: 'Make a tape or chalk line on the floor.' },
        {
          art: 'emoji:🦶',
          say: 'Walk heel to toe, slowly. Wobbles mean your balance is learning!',
          timerSec: 45,
          after: 'You found your balance one careful step at a time.',
        },
        {
          art: 'emoji:✈️',
          say: 'Airplane arms out wide. Make another slow pass.',
          timerSec: 45,
          after: 'Smooth airplane arms! Nice recovery from every wobble.',
        },
        {
          art: 'emoji:↩️',
          say: 'Turn around and walk backwards with tiny steps.',
          timerSec: 60,
          after: 'Tiny backwards steps. Calm, careful, and strong!',
        },
        { art: 'emoji:🌟', say: 'Finish with your biggest superstar pose!' },
      ],
    },
    {
      id: 'outdoor',
      title: 'Log and Curb',
      type: 'steps',
      praise: 'Nice recovery. Your spotter is right there!',
      cheer: 'Ta-da! You and your grown-up finished the outdoor balance trail!',
      endTitle: 'Log and Curb',
      endArt: 'emoji:🎉',
      againLabel: 'AGAIN',
      doneLabel: 'DONE',
      steps: [
        { art: 'emoji:🪵', say: 'With a grown-up spotter, find a low log or curb.' },
        {
          art: 'emoji:🤝',
          say: 'Hold your spotter\'s hand and make one slow pass.',
          timerSec: 60,
          after: 'Hand in hand, you practiced safe balance.',
        },
        {
          art: 'emoji:🧘',
          say: 'Keep your spotter close. Try one slow pass on your own.',
          timerSec: 60,
          after: 'Slow and focused! Wobbles helped your balance learn.',
        },
        { art: 'emoji:⏸️', say: 'Stop in the middle and balance for five slow breaths.' },
        { art: 'emoji:🎉', say: 'Hop off to a safe landing and say ta-da!' },
      ],
    },
  ],
};
