export default {
  id: 'animal-walk-cards',
  engine: 'coach-timer',
  title: 'Animal Walk Cards',
  splashEmoji: 'emoji:🐻',
  theme: { world: 'field-journal', background: './assets/bg.jpg' },
  voice: {
    intro: 'Welcome to animal school! Show me how each animal moves and sounds!',
    praise: 'Wild moves! You made that animal proud!',
    cheer: 'The animal parade was wild and wonderful!',
  },
  modes: [
    {
      id: 'learn',
      title: 'Animal School',
      type: 'steps',
      praise: 'Wild moves! You made that animal proud!',
      cheer: 'Animal school complete! Every creature taught your body a new move!',
      endTitle: 'Animal School',
      endArt: 'emoji:🐾',
      againLabel: 'AGAIN',
      doneLabel: 'DONE',
      steps: [
        {
          art: 'emoji:🐻',
          say: 'Bear crawl! Hands and feet down, bottom up. Roar like a bear!',
          timerSec: 30,
          after: 'Big bear roar! Strong crawling!',
        },
        {
          art: 'emoji:🐸',
          say: 'Frog jump! Crouch low, then leap. Ribbit!',
          timerSec: 30,
          after: 'Ribbit! What a frog leap!',
        },
        {
          art: 'emoji:🦀',
          say: 'Crab walk! Belly to the sky. Click-click your crab claws!',
          timerSec: 30,
          after: 'Click-click! That crab was strong!',
        },
        { art: 'emoji:🦩', say: 'Flamingo stand! Lift one leg and count five slow flamingo breaths. Hmmmm.' },
        { art: 'emoji:🐢', say: 'Cool down with a slow turtle stretch. Tuck in, then stretch long.' },
      ],
    },
    {
      id: 'parade',
      title: 'Animal Parade',
      type: 'steps',
      praise: 'Keep the parade moving!',
      cheer: 'The whole animal parade made it to the finish!',
      endTitle: 'Animal Parade',
      endArt: 'emoji:🎪',
      againLabel: 'AGAIN',
      doneLabel: 'DONE',
      steps: [
        {
          art: 'emoji:🐻',
          say: 'Parade bear! Crawl on hands and feet. ROAR!',
          timerSec: 20,
          after: 'Roar! Bear joins the parade!',
        },
        {
          art: 'emoji:🐸',
          say: 'Parade frog! Crouch and leap. Ribbit!',
          timerSec: 20,
          after: 'Ribbit! Frog joins the parade!',
        },
        {
          art: 'emoji:🦀',
          say: 'Parade crab! Belly up and walk. Click-click!',
          timerSec: 20,
          after: 'Click-click! Crab joins the parade!',
        },
        {
          art: 'emoji:🦩',
          say: 'Parade flamingo! One leg and a flamingo hum. Hmmmm!',
          timerSec: 20,
          after: 'Hmmmm! Flamingo joins the parade!',
        },
        { art: 'emoji:🎪', say: 'Invite your family to join the animal parade line!' },
      ],
    },
  ],
};
