export default {
  id: 'sticker-line-challenge',
  engine: 'trace-path',
  title: 'Sticker Line Challenge',
  splashEmoji: '⭐',
  // Paper Garden art world (docs/art-direction.md)
  theme: { world: 'paper-garden', background: './assets/bg.jpg' },
  endArt: 'emoji:🌟',
  traveler: 'emoji:⭐',
  strokeColor: '#e873a4',
  tolerance: 76,
  startMarker: '⭐',
  copy: {
    home: 'Home',
    replay: 'Hear it again',
    playAgain: 'Play Again',
  },
  voice: {
    intro: 'Pick a sticker path to decorate!',
    nudge: 'Find the dotted line and keep sticking stars.',
    cheer: 'Your whole sticker chain is wiggling with joy!',
    yums: [
      'Beautiful sticker tracing!',
      'Your careful finger followed every dot!',
      'What a lovely sticker line!',
    ],
  },
  modes: [
    {
      id: 'waves',
      title: 'Wavy Lines',
      prompt: 'Trace the wavy line. Stick a star on every dot!',
      rounds: 3,
      paths: [
        {
          id: 'little-wave',
          name: 'little wave',
          prompt: 'Trace the gentle wavy line. Stick a star on every dot!',
          say: 'A neat little wave of stickers!',
          points: [[120, 500], [260, 420], [400, 500], [540, 580], [680, 500], [820, 420], [930, 500]],
        },
        {
          id: 'bouncy-wave',
          name: 'bouncy wave',
          prompt: 'Trace the bouncy wavy line. Stick a star on every dot!',
          say: 'Beautiful bouncy waves!',
          points: [[110, 500], [250, 330], [390, 500], [530, 670], [670, 500], [810, 330], [930, 500]],
        },
        {
          id: 'big-wave',
          name: 'big wave',
          prompt: 'Trace the big wavy line. Stick a star on every dot!',
          say: 'You followed every big curve!',
          points: [[100, 520], [230, 260], [360, 520], [490, 760], [620, 520], [750, 260], [900, 520]],
        },
      ],
    },
    {
      id: 'zigzags',
      title: 'Zigzag Trails',
      prompt: 'Trace the zigzag trail from left to right.',
      rounds: 3,
      strokeColor: '#f28c4b',
      paths: [
        {
          id: 'two-turns',
          name: 'two-turn zigzag',
          prompt: 'Trace up, down, and up along the sticker dots.',
          say: 'What a pointy turn!',
          points: [[140, 680], [390, 300], [640, 680], [890, 300]],
        },
        {
          id: 'three-turns',
          name: 'three-turn zigzag',
          prompt: 'Follow the zigzag and make each pointy turn.',
          say: 'Those corners are crisp and pointy!',
          points: [[110, 680], [310, 300], [510, 680], [710, 300], [910, 680]],
        },
        {
          id: 'four-turns',
          name: 'four-turn zigzag',
          prompt: 'Steady finger. Trace all the pointy turns.',
          say: 'What a wonderful row of pointy turns!',
          points: [[90, 690], [250, 280], [410, 690], [570, 280], [730, 690], [910, 280]],
        },
      ],
    },
    {
      id: 'loops',
      title: 'Loop-the-Loops',
      prompt: 'Trace the loop all the way around.',
      rounds: 3,
      strokeColor: '#8c6bc7',
      paths: [
        {
          id: 'big-circle',
          name: 'big circle',
          prompt: 'Go round and round to make one big sticker loop.',
          say: 'A lovely round loop!',
          points: [[500, 160], [720, 200], [840, 400], [800, 640], [600, 820], [360, 800], [170, 610], [180, 360], [300, 190], [500, 160]],
        },
        {
          id: 'tall-loop',
          name: 'tall loop',
          prompt: 'Trace the tall loop. Loops are how letters like l begin.',
          say: 'That tall loop could begin a letter l!',
          points: [[420, 820], [330, 650], [350, 390], [500, 160], [650, 390], [650, 650], [500, 760], [420, 650]],
        },
        {
          id: 'side-loop',
          name: 'sideways loop',
          prompt: 'Curl around the sideways loop. Loops help letters like e begin.',
          say: 'That curly loop could begin a letter e!',
          points: [[180, 520], [340, 340], [560, 350], [720, 500], [580, 650], [360, 650], [250, 500], [420, 410], [650, 410], [820, 540]],
        },
      ],
    },
  ],
};
