const numberWords = {
  1: 'one',
  2: 'two',
  3: 'three',
  4: 'four',
  5: 'five',
  6: 'six',
  7: 'seven',
  8: 'eight',
  9: 'nine',
  10: 'ten',
  11: 'eleven',
  12: 'twelve',
  13: 'thirteen',
  14: 'fourteen',
  15: 'fifteen',
  16: 'sixteen',
  17: 'seventeen',
  18: 'eighteen',
  19: 'nineteen',
};

export default {
  id: 'teen-bead-builder',
  title: 'Teen Bead Builder',
  artWorld: 'toy-table / claymation workshop',
  numberWords,
  colors: ['gold', 'coral', 'teal', 'green', 'blue', 'cream'],
  modes: [
    {
      id: 'build',
      title: 'Bundle & Build',
      skill: 'compose teen numbers as one ten and some ones',
      rounds: [11, 14, 17, 19],
    },
    {
      id: 'match',
      title: 'Bead Detective',
      skill: 'match a base-ten bead model to its teen numeral',
      rounds: [12, 15, 18, 13, 16],
    },
  ],
  voice: {
    welcome: 'Pick one bead game to play.',
    buildIntro: 'First, let us make a ten. Add ten golden beads.',
    addBead: 'Add a golden bead.',
    bundleNudge: 'Bring the bead to the glowing ten frame.',
    tenMade: 'Ten ones bundle into one ten!',
    countOn: 'Now count on from ten.',
    matchIntro: 'Look at the beads. Which teen number do they show?',
    chooseNumber: 'Which number do the beads show?',
    tryAgain: 'Count the ones after ten. Try another number.',
    finish: 'Beautiful building! You really know your teen numbers.',
    back: 'Pick another way to play.',
  },
};
