export function createSweepBoard({ host, mode, rng = Math.random, timers, reducedMotion = false, onCapture = () => {}, onComplete = () => {}, onActivity = () => {} }) {
  const W = 1600, H = 1200;
  const ownedTimers = new Set();
  let dead = false, active = false, completed = false, pointerId = null, offset = { x: 0, y: 0 };
  const pressed = new Map();
  const broom = { x: mode.broomStart.x, y: mode.broomStart.y, rotation: 0 };
  const pieces = (mode.debris || []).map(p => {
    const jitter = p.jitter == null ? 24 : Math.max(0, Number(p.jitter) || 0);
    return { ...p, x: p.x + (rng() - .5) * jitter, y: p.y + (rng() - .5) * jitter, captured: false, rotation: p.rotation == null ? (rng() - .5) * 6 : p.rotation, el: null };
  });
  const mk = (tag, cls, src, target) => { const e = document.createElement(tag); e.className = cls; if (src) e.src = src; e.draggable = false; if (target) e.dataset.target = target; return e; };
  host.classList.add('sweep-board');
  host.style.setProperty('--sweep-width', W); host.style.setProperty('--sweep-height', H);
  const bg = mk('img', 'sweep-background', mode.assets && mode.assets.background); bg.alt = ''; host.appendChild(bg);
  const portraitQuery = typeof matchMedia === 'function' ? matchMedia('(orientation: portrait)') : null;
  const refreshBackground = () => { if (!dead) bg.src = portraitQuery && portraitQuery.matches && mode.assets && mode.assets.backgroundPortrait ? mode.assets.backgroundPortrait : (mode.assets && mode.assets.background) || ''; };
  refreshBackground(); if (portraitQuery) portraitQuery.addEventListener ? portraitQuery.addEventListener('change', refreshBackground) : portraitQuery.addListener(refreshBackground);
  const target = mk('img', 'sweep-target', mode.assets && mode.assets.target, mode.target.id || 'basket'); target.alt = mode.target.label || 'Trail basket'; host.appendChild(target);
  const broomSize = mode.broomSize || 150;
  const broomEl = mk('button', 'sweep-broom', null, 'broom'); broomEl.type = 'button'; broomEl.setAttribute('aria-label', 'Broom');
  const broomImg = mk('img', 'sweep-broom-image', mode.assets && mode.assets.broom); broomImg.alt = ''; broomEl.appendChild(broomImg); host.appendChild(broomEl);
  pieces.forEach(p => { p.el = mk('img', 'sweep-debris', p.src, `debris-${p.id}`); p.el.alt = `Trail piece ${p.id}`; host.appendChild(p.el); });
  const helper = mode.helper && mode.assets && mode.assets.helper ? mk('img', 'sweep-helper', mode.assets.helper) : null; if (helper) { helper.alt = ''; host.appendChild(helper); }
  const pos = (e, x, y, size, rot = 0) => { e.style.setProperty('--x', `${x / W * 100}%`); e.style.setProperty('--y', `${y / H * 100}%`); if (size) e.style.setProperty('--size', `${size / W * 100}%`); e.style.setProperty('--rotation', `${rot}deg`); };
  const render = () => { pos(target, mode.target.x, mode.target.y, mode.target.size); pos(broomEl, broom.x, broom.y, broomSize, broom.rotation); pieces.forEach(p => { pos(p.el, p.x, p.y, p.size, p.rotation || 0); p.el.classList.toggle('is-captured', p.captured); }); if (helper) pos(helper, mode.helper.x, mode.helper.y, mode.helper.size); };
  const later = (fn, ms = 0) => { if (dead) return; let id; const cb = () => { ownedTimers.delete(id); if (!dead) fn(); }; id = timers && timers.after ? timers.after(ms, cb) : setTimeout(cb, ms); ownedTimers.add(id); return id; };
  const cancelTimer = id => { if (timers && timers.clear) timers.clear(id); else clearTimeout(id); ownedTimers.delete(id); };
  const clamp = (v, a, b) => Math.max(a, Math.min(b, v));
  const segDist = (ax, ay, bx, by, px, py) => { const dx = bx - ax, dy = by - ay, d = dx * dx + dy * dy; const t = d ? clamp(((px - ax) * dx + (py - ay) * dy) / d, 0, 1) : 0; return Math.hypot(px - (ax + t * dx), py - (ay + t * dy)); };
  const moveBroom = (x, y) => { if (dead) return; const old = { x: broom.x, y: broom.y }; broom.x = clamp(x, mode.bounds.left, mode.bounds.right); broom.y = clamp(y, mode.bounds.top, mode.bounds.bottom); const dx = broom.x - old.x, dy = broom.y - old.y; if (dx || dy) broom.rotation = Math.atan2(dy, dx) * 180 / Math.PI + 90;
    pieces.forEach(p => { if (p.captured || segDist(old.x, old.y, broom.x, broom.y, p.x, p.y) > mode.brushRadius + p.size / 2) return; const pieceOld = { x: p.x, y: p.y }; const mass = Math.max(0.25, p.mass || 1); p.x = clamp(p.x + dx / mass, mode.bounds.left, mode.bounds.right); p.y = clamp(p.y + dy / mass, mode.bounds.top, mode.bounds.bottom); const tx = mode.target.x - p.x, ty = mode.target.y - p.y, dot = dx * tx + dy * ty; if (dot > 0) { const n = Math.hypot(tx, ty) || 1; p.x = clamp(p.x + tx / n * Math.min(2, Math.hypot(dx, dy) * .08), mode.bounds.left, mode.bounds.right); p.y = clamp(p.y + ty / n * Math.min(2, Math.hypot(dx, dy) * .08), mode.bounds.top, mode.bounds.bottom); } if (Math.hypot(p.x - mode.target.x, p.y - mode.target.y) <= mode.target.radius || segDist(pieceOld.x, pieceOld.y, p.x, p.y, mode.target.x, mode.target.y) <= mode.target.radius) { p.x = mode.target.x; p.y = mode.target.y; capture(p); } }); render(); if (dx || dy) { try { onActivity({ x: broom.x, y: broom.y }); } catch (_) {} } };
  const capture = p => { if (p.captured || dead) return; p.captured = true; const remaining = pieces.filter(q => !q.captured).length; try { onCapture({ id: p.id, remaining, piece: p }); } catch (_) {} if (!remaining && !completed) { completed = true; later(() => { try { onComplete(); } catch (_) {} }); } };
  const point = ev => { const r = host.getBoundingClientRect(); return { x: (ev.clientX - r.left) * W / (r.width || W), y: (ev.clientY - r.top) * H / (r.height || H) }; };
  const detachPointerListeners = () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', up); window.removeEventListener('pointercancel', up); };
  const end = id => { if (id != null && id !== pointerId) { pressed.delete(id); return; } pressed.delete(id); const next = [...pressed.keys()][0]; if (next != null) { pointerId = next; const p = pressed.get(next); offset = { x: p.x - broom.x, y: p.y - broom.y }; return; } active = false; pointerId = null; detachPointerListeners(); };
  const up = ev => end(ev.pointerId);
  const move = ev => { if (!pressed.has(ev.pointerId)) return; const p = point(ev); pressed.set(ev.pointerId, p); if (!active || ev.pointerId !== pointerId) return; moveBroom(p.x - offset.x, p.y - offset.y); };
  const start = ev => { if (dead || (ev.pointerType === 'mouse' && ev.button !== 0)) return; const p = point(ev); pressed.set(ev.pointerId, p); if (!active) { offset = { x: p.x - broom.x, y: p.y - broom.y }; pointerId = ev.pointerId; active = true; window.addEventListener('pointermove', move); window.addEventListener('pointerup', up); window.addEventListener('pointercancel', up); } else if (ev.pointerType === 'touch') { pointerId = ev.pointerId; offset = { x: p.x - broom.x, y: p.y - broom.y }; } try { broomEl.setPointerCapture(ev.pointerId); } catch (_) {} ev.preventDefault(); };
  const cancel = () => { pressed.clear(); active = false; pointerId = null; detachPointerListeners(); };
  broomEl.addEventListener('pointerdown', start); window.addEventListener('blur', cancel); document.addEventListener('visibilitychange', cancel); window.addEventListener('pagehide', cancel); window.addEventListener('resize', cancel);
  broomEl.addEventListener('keydown', ev => { const step = 28; let x = broom.x, y = broom.y; if (ev.key === 'ArrowLeft') x -= step; else if (ev.key === 'ArrowRight') x += step; else if (ev.key === 'ArrowUp') y -= step; else if (ev.key === 'ArrowDown') y += step; else if (ev.key === 'Enter' || ev.key === ' ') { moveBroom(broom.x + (mode.target.x - broom.x) * .12, broom.y + (mode.target.y - broom.y) * .12); ev.preventDefault(); return; } else return; moveBroom(x, y); ev.preventDefault(); }); render();
  const getState = () => ({ mode: { id: mode.id }, broom: { x: broom.x, y: broom.y, rotation: broom.rotation }, active, completed, remaining: pieces.filter(p => !p.captured).length, pieces: pieces.map(p => ({ id: p.id, x: p.x, y: p.y, captured: p.captured })) });
  const liftBroomTo = (x, y) => { broom.x = clamp(x, mode.bounds.left, mode.bounds.right); broom.y = clamp(y, mode.bounds.top, mode.bounds.bottom); render(); };
  const sweep = p => { if (!p || p.captured || dead) return { accepted: false, captured: false }; let i = 0; while (!p.captured && i++ < 24) { const dx = mode.target.x - p.x, dy = mode.target.y - p.y, n = Math.hypot(dx, dy) || 1; liftBroomTo(p.x - dx / n * (mode.brushRadius + p.size / 2 + 12), p.y - dy / n * (mode.brushRadius + p.size / 2 + 12)); moveBroom(p.x + dx / n * (mode.brushRadius + p.size + 100), p.y + dy / n * (mode.brushRadius + p.size + 100)); } return { accepted: true, captured: p.captured }; };
  const api = { destroy() { if (dead) return; dead = true; cancel(); broomEl.removeEventListener('pointerdown', start); window.removeEventListener('blur', cancel); document.removeEventListener('visibilitychange', cancel); window.removeEventListener('pagehide', cancel); window.removeEventListener('resize', cancel); if (portraitQuery) portraitQuery.removeEventListener ? portraitQuery.removeEventListener('change', refreshBackground) : portraitQuery.removeListener(refreshBackground); ownedTimers.forEach(cancelTimer); host.classList.remove('sweep-board'); host.style.removeProperty('--sweep-width'); host.style.removeProperty('--sweep-height'); host.replaceChildren(); }, cancel, getState, getTargets() { const live = e => { const r = e.getBoundingClientRect(); return { id: e.dataset.target, rect: { x: r.x, y: r.y, w: r.width, h: r.height }, role: e === broomEl ? 'neutral' : 'correct' }; }; return [...pieces.filter(p => !p.captured && p.el.getBoundingClientRect().width).map(p => live(p.el)), live(target), live(broomEl)]; }, moveBroom, debugSweep(id) { return sweep(pieces.find(q => q.id === id)); }, win() { const result = pieces.filter(p => !p.captured).map(sweep); return Promise.resolve(result); }, nudge() { const p = pieces.filter(q => !q.captured).sort((a, b) => Math.hypot(a.x - broom.x, a.y - broom.y) - Math.hypot(b.x - broom.x, b.y - broom.y))[0]; if (!p) return; p.el.classList.add('is-nudge'); target.classList.add('is-nudge'); later(() => { p.el.classList.remove('is-nudge'); target.classList.remove('is-nudge'); }, reducedMotion ? 0 : 500); } }; return api;
}
