export default {
  id: 'big-paper-murals',
  engine: 'coach-timer',
  title: 'Big Paper Murals',
  splashEmoji: 'emoji:🎨',
  theme: { world: 'paper-garden', background: './assets/bg.jpg' },
  voice: {
    intro: 'Artists, get ready to make a mural with big, bold movements!',
    praise: 'Beautiful art move!',
    cheer: 'Gallery open! Your giant mural is amazing!',
  },
  modes: [
    {
      id: 'solo',
      title: 'My Mural',
      type: 'steps',
      praise: 'Beautiful art move!',
      cheer: 'Gallery open! Your giant mural is amazing!',
      endTitle: 'My Mural',
      endArt: 'emoji:🖼️',
      againLabel: 'AGAIN',
      doneLabel: 'DONE',
      steps: [
        { art: 'emoji:📜', say: 'Roll out your big paper and ask a grown-up to tape the corners.' },
        {
          art: 'emoji:💪',
          say: 'Warm up with giant arm circles. Make them huge!',
          timerSec: 20,
          after: 'Big circles! Your artist shoulders are ready!',
        },
        {
          art: 'emoji:➰',
          say: 'Draw huge loops with your whole arm!',
          timerSec: 60,
          after: 'Wow! Those loops are mural-sized!',
        },
        {
          art: 'emoji:🔍',
          say: 'Fill one corner with tiny details.',
          timerSec: 60,
          after: 'Wonderful tiny details!',
        },
        { art: 'emoji:✍️', say: 'Sign your masterpiece BIG!' },
      ],
    },
    {
      id: 'together',
      title: 'Mural Party',
      type: 'steps',
      praise: 'Kind artists make great murals together!',
      cheer: 'Gallery open! Walk around your mural and celebrate every artist!',
      endTitle: 'Mural Party',
      endArt: 'emoji:🖼️',
      againLabel: 'AGAIN',
      doneLabel: 'DONE',
      steps: [
        { art: 'emoji:🧑‍🤝‍🧑', say: 'Everyone pick a corner of the big paper.' },
        {
          art: 'emoji:🖍️',
          say: 'Draw in your corner. Fill it with your ideas!',
          timerSec: 90,
          after: 'Every corner is bursting with art!',
        },
        {
          art: 'emoji:🔄',
          say: 'Swap spots! Add to a friend\'s part kindly.',
          timerSec: 90,
          after: 'You shared the space and made the mural grow!',
        },
        {
          art: 'emoji:🛤️',
          say: 'Connect all the corners with one long road or river.',
          timerSec: 60,
          after: 'One giant line connects the whole mural!',
        },
        { art: 'emoji:🖼️', say: 'Gallery opening! Walk around the mural and say your favorite part.' },
      ],
    },
  ],
};
