// game.js — Bug Hotel Observer's play field: the hotel, the rooms, the seeded
// placement, and the lens ↔ hotspot reveal contract.
//
// It owns everything that lives in ART space. It does NOT own screens, the HUD,
// the journal spread or QLOBE_DEBUG — those are js/main.js and js/journal-ui.js.
// The two meet at `createField`'s `ctx` (things main knows: the time scale, the
// seed, the mode, the round, the HUD rects, the yes deck) and `on` (things main
// must react to: a room was picked, a bug was revealed, the target was greeted).
//
// Contract references are to games/bug-hotel-observer/game-design.md.

import { createScene } from '../../../shared/js/hotspot-scene.js';
import { createLens } from '../../../shared/js/magnifier-lens.js';
import { resolveArt, imgEl } from './art.js';

// ---------------------------------------------------------------------------
// §4.3 — the game's ONLY PRNG. FNV-1a over a concatenated string, shared by the
// nook pick, the bug order and both voice decks, so `seed(n)` pins all four.
// (Same function as games/rhyming-detective/js/game.js — deliberately copied
// rather than shared: it is six lines, and a shared PRNG whose stream changed
// would silently re-roll every QA baseline in two games at once.)
// ---------------------------------------------------------------------------

export function fnv1a(str) {
  let h = 2166136261 >>> 0;
  const s = String(str);
  for (let i = 0; i < s.length; i += 1) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619) >>> 0;
  }
  return h >>> 0;
}

/** Deterministic Fisher-Yates driven by the same hash. Returns a new array. */
export function seededShuffle(list, seedNum) {
  const out = list.slice();
  let h = fnv1a(String(seedNum));
  for (let i = out.length - 1; i > 0; i -= 1) {
    h = fnv1a(`${h}`);
    const j = h % (i + 1);
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

/**
 * §3.6 — a shuffled deck drawn without replacement, reshuffled when exhausted,
 * never repeating the last card across the reshuffle boundary.
 */
export function createDeck(keys, seedNum) {
  const source = (keys || []).slice();
  let pile = [];
  let last = null;
  let round = 0;

  function refill() {
    pile = seededShuffle(source, `${seedNum}:${round}`);
    round += 1;
    if (pile.length > 1 && pile[0] === last) {
      [pile[0], pile[1]] = [pile[1], pile[0]];
    }
  }

  return {
    next() {
      if (!source.length) return null;
      if (!pile.length) refill();
      last = pile.shift();
      return last;
    },
    reseed(nextSeed) {
      seedNum = nextSeed;
      round = 0;
      pile = [];
    },
  };
}

/**
 * §4.2 — the round index is DERIVED, never stored:
 *
 *     round = min over rooms of ( that room's bugs present in the journal )
 *
 * so it survives a reload for free, resets when the journal is cleared, and
 * cannot disagree with the sticker grid. Exported because main.js's
 * `getState()` and `resetJournal()` both need exactly this number and there
 * must not be two ways to compute it.
 */
export function deriveRound(config, journal) {
  const rooms = config.rooms || [];
  if (!rooms.length) return 0;
  let min = Infinity;
  for (const room of rooms) {
    let owned = 0;
    for (const bugId of room.bugs || []) if (journal.has(bugId)) owned += 1;
    if (owned < min) min = owned;
  }
  return Number.isFinite(min) ? min : 0;
}

/**
 * §4.2 — round `r` targets `room.bugs[r % targetCycle]` in every room. The
 * table in the design doc is generated by this line and restated nowhere.
 */
export function targetForRoom(room, round, cycle = 3) {
  const bugs = room.bugs || [];
  if (!bugs.length) return null;
  const n = Math.max(1, Math.min(cycle, bugs.length));
  return bugs[((round % n) + n) % n];
}

/**
 * §4.3 — three of the four authored nooks, and which bug sits in each.
 * `(seed, mode, room, round)` fully determines the layout, so `seed(42)` pins
 * every room in every round for QA and two real sessions differ. `mode` is in
 * the hash on purpose: a child who learned where the ladybug was in Bug Hunt
 * still has to search for it in Bug Detective.
 *
 * There is NO jitter. Zone centres are authored against the real plates (P6);
 * a random offset would push a bug onto a paper edge.
 */
export function placeBugs(room, { seed, mode, round, placed = 3 }) {
  const zones = room.zones || [];
  const bugs = room.bugs || [];
  const key = `${seed}|${mode}|${room.id}|${round}`;
  const n = Math.min(placed, zones.length, bugs.length);
  const nooks = seededShuffle(zones, `${key}|zones`).slice(0, n);
  const order = seededShuffle(bugs, `${key}|bugs`).slice(0, n);
  return order.map((bugId, i) => ({
    bugId,
    zone: nooks[i].name,
    artX: Number(nooks[i].x),
    artY: Number(nooks[i].y),
  }));
}

// ---------------------------------------------------------------------------
// the play field
// ---------------------------------------------------------------------------

function wait(ms) {
  return new Promise((resolve) => setTimeout(resolve, Math.max(0, ms)));
}

/**
 * @param {object} o
 * @param {HTMLElement} o.mount  the #stage element the scene may fill
 * @param {object} o.config      parsed config.json
 * @param {object} o.voice       js/voice.js
 * @param {object} o.sfx         the mute-gated sfx facade from main
 * @param {object} o.ctx         getters main owns: timeScale, seed, mode,
 *                               modeDef, round, screen, reserves, yesKey
 * @param {object} o.on          callbacks into main: reflow, room, reveal,
 *                               target, roommate
 */
export function createField({ mount, config, voice, sfx, ctx, on }) {
  const tuning = config.tuning || {};
  const lensCfg = config.lens || {};
  const artW = (config.art && config.art.w) || 1600;
  const artH = (config.art && config.art.h) || 1200;
  const bugById = new Map((config.bugs || []).map((b) => [b.id, b]));
  const roomById = new Map((config.rooms || []).map((r) => [r.id, r]));

  const scene = createScene(mount, {
    artW,
    artH,
    minHit: Number(tuning.minHitCssPx) || 96,
    ariaLabel: 'The bug hotel. Drag the magnifying glass to look for bugs.',
    className: 'bh-scene',
  });

  // A decoration-only layer beside the scene root, inside the same mount. It
  // holds the "this room is done" bug badges on the hotel screen: they are
  // authored art (the bug's own happy frame) that must never be a hit target,
  // and a hotspot carries exactly one sprite. §8.1 rows 3 and 10 keep art and
  // hit target separate; this is that rule applied to a second picture.
  const fx = document.createElement('div');
  fx.className = 'bh-fx';
  fx.setAttribute('aria-hidden', 'true');
  mount.appendChild(fx);

  let lens = null;
  let view = 'none';            // 'none' | 'hotel' | 'room'
  let roomDef = null;
  let placements = [];          // [{ bugId, zone, artX, artY, handle }]
  let targetId = null;
  let plateUrl = null;
  const revealed = new Set();   // bug ids visible in the BASE scene, this room
  const doneRooms = new Map();  // roomId -> bugId whose happy badge is shown
  let layout = 'wide';
  let lastReflow = null;
  let token = 0;                // supersedes every in-flight choreography
  let wrongTaps = 0;
  let lastCloserAt = -Infinity;
  let firstRevealDone = false;
  let seenAnyRoom = false;      // §3.5 — prompt-lens plays on the first room only
  // The plate, the hotspots and the lens all land asynchronously, and main.js
  // flips the screen BEFORE they do so the HUD paints on the first frame. This
  // is the flag that says the field is actually playable — QLOBE_DEBUG reports
  // it, so a harness waits on the truth instead of racing a screen name.
  let mounted = false;
  const timers = new Set();
  let offDwell = null;
  let offMove = null;

  const T = (ms) => ms * ctx.timeScale();

  function later(ms, fn) {
    const id = setTimeout(() => { timers.delete(id); fn(); }, Math.max(0, T(ms)));
    timers.add(id);
    return id;
  }

  function cancelTimers() {
    for (const id of timers) clearTimeout(id);
    timers.clear();
  }

  // -- geometry --------------------------------------------------------------

  function bugBox(p) {
    const size = Number(bugById.get(p.bugId)?.artSize) || 190;
    return { x: p.artX, y: p.artY, w: size, h: size };
  }

  function roomBox(room) {
    const h = room.exteriorHotspot || {};
    return { x: Number(h.x), y: Number(h.y), w: Number(h.w) || 280, h: Number(h.h) || 260 };
  }

  // -- the done badges (hotel screen) ---------------------------------------

  /**
   * The happy frame of a finished room's target, tucked into the plaque's
   * corner at 46 %. Positioned from the SETTLED hotspot rect, not from the
   * authored art box: the scene inflates a small hit box to `minHit` and slides
   * it out from under the HUD, and a badge pinned to the authored centre would
   * drift off its own plaque on a portrait crop.
   */
  function paintBadges() {
    if (view !== 'hotel') { fx.replaceChildren(); return; }
    const origin = mount.getBoundingClientRect();
    for (const el of fx.children) {
      const handle = scene.get(el.dataset.room);
      const r = handle && handle.rect();
      if (!r || !(r.w > 0)) { el.hidden = true; continue; }
      const size = Math.max(48, r.w * 0.46);
      el.hidden = false;
      el.style.width = `${size}px`;
      el.style.height = `${size}px`;
      el.style.left = `${r.x + r.w - size * 0.72 - origin.left}px`;
      el.style.top = `${r.y + r.h - size * 0.86 - origin.top}px`;
    }
  }

  function buildBadges() {
    fx.replaceChildren();
    for (const [roomId, bugId] of doneRooms) {
      const bug = bugById.get(bugId);
      if (!bug) continue;
      const el = imgEl(bug.sprites && bug.sprites.happy, 'bh-badge');
      el.dataset.room = roomId;
      fx.appendChild(el);
    }
    paintBadges();
  }

  // -- reflow ----------------------------------------------------------------

  scene.onReflow((payload) => {
    lastReflow = payload;
    layout = payload.layoutHint;
    paintBadges();
    // A resize NEVER re-rolls a placement (§2.9) — the art boxes are authored
    // and the module re-derives the screen rects itself, so there is nothing to
    // re-place here. The lens re-clamps its own centre off the same reflow.
    if (on.reflow) on.reflow(payload, layout);
  });

  scene.setReserve(() => ctx.reserves() || []);

  // -- the lens --------------------------------------------------------------

  async function ensureLens() {
    if (lens) return lens;
    const frameUrl = await resolveArt(lensCfg.sprite);
    if (lens) return lens;              // a second entry raced us; keep the first
    // §5.2 — `frame.scale` and `frame.anchor` are MEASURED from the sprite
    // (tools/fix-cutouts.py `glass_aperture`), not guessed: they are what makes
    // the authored glass hole land exactly on the clip circle.
    const frameCfg = lensCfg.frame || {};
    lens = createLens(scene, {
      zoom: Number(lensCfg.zoom) || 1.6,
      glassD: Number(lensCfg.glassD) || 320,
      gripOffset: Number(lensCfg.gripOffset) || 44,
      gripDir: lensCfg.gripDir || undefined,
      gripSize: Number(lensCfg.gripSize) || undefined,
      gripMinCssPx: Number(lensCfg.gripMinCssPx) || 140,
      glintMs: Number(lensCfg.glintMs) || 900,
      dwellMs: Number(lensCfg.dwellMs) || 600,
      dwellRadiusArt: Number(lensCfg.dwellRadiusArt) || 150,
      frame: frameUrl ? { url: frameUrl, scale: frameCfg.scale, anchor: frameCfg.anchor } : null,
      start: lensCfg.startArt || { x: artW / 2, y: artH / 2 },
      ariaLabel: 'magnifying glass',
      className: 'bh-lens',
    });
    lens.setReserve(() => ctx.reserves() || []);

    // §5.2.7 — the reveal hand-off. The lens reports the dwell; the GAME
    // decides what a reveal means. The module never touches a hotspot.
    offDwell = lens.onDwell((d) => { void reveal(d.id); });

    // §9.3 — "getting closer" is a proximity nudge, not a hint: it fires at
    // most once every `gettingCloserCooldownMs` and never says which way.
    offMove = lens.onMove((c) => {
      if (view !== 'room' || ctx.screen() !== 'room') return;
      const radius = Number(tuning.gettingCloserRadiusArt) || 320;
      const cool = Number(tuning.gettingCloserCooldownMs) || 6000;
      const now = performance.now();
      if (now - lastCloserAt < T(cool)) return;
      for (const p of placements) {
        if (revealed.has(p.bugId)) continue;
        if (Math.hypot(c.x - p.artX, c.y - p.artY) <= radius) {
          lastCloserAt = now;
          voice.say('getting-closer');
          return;
        }
      }
    });
    return lens;
  }

  // -- §5.2.7 / §9.3 the reveal ---------------------------------------------

  /**
   * A bug crosses from the magnified world into the base world. PERMANENT: it
   * is never re-hidden, not by a resize, not by leaving and re-entering the
   * room in the same round. Idempotent, because a dwell and a debug reveal can
   * land on the same bug in the same frame.
   *
   * P6: the bug is RETIRED from the dwell rather than removed from the glass.
   * The glass paints its own opaque copy of the world, so a bug taken out of it
   * disappeared at the very moment the child found it and only came back when
   * the glass moved away. Now it is in both worlds at once — magnified under
   * the glass, life-size beside it — which is what a magnifier does.
   */
  async function reveal(bugId) {
    if (view !== 'room' || revealed.has(bugId)) return false;
    const p = placements.find((q) => q.bugId === bugId);
    if (!p || !p.handle) return false;
    const mine = token;
    revealed.add(bugId);

    if (lens) lens.markFound(bugId);
    const bug = bugById.get(bugId);
    const url = await resolveArt(bug && bug.sprites && bug.sprites.idle);
    if (mine !== token) return false;
    // A sprite that never resolves costs the child a picture, not a turn
    // (§10): the hotspot is enabled either way.
    if (url) await p.handle.setSprite(url);
    if (mine !== token) return false;

    // The one public call that names the button now that it means something.
    // Re-adding an existing id updates in place and returns the SAME handle;
    // omitting `sprite` leaves the sprite exactly as loaded above.
    scene.addHotspot({ id: bugId, ...bugBox(p), alt: bugId, z: 3 });
    p.handle.setEnabled(true);
    p.handle.pop({ ms: T(Number(tuning.popMs) || 340) });
    sfx.sparkle();

    if (!firstRevealDone) {
      firstRevealDone = true;
      voice.say('found-tap');
    }
    if (on.reveal) on.reveal(bugId, revealed.size);
    return true;
  }

  // -- §9.4 tapping a found bug ---------------------------------------------

  function bugVoice(bugId, key) {
    const bug = bugById.get(bugId);
    return (bug && bug.voice && bug.voice[key]) || null;
  }

  async function greet(bugId) {
    const mine = token;
    const p = placements.find((q) => q.bugId === bugId);
    const bug = bugById.get(bugId);
    if (!p || !p.handle || !bug) return;
    sfx.pop();

    const happy = await resolveArt(bug.sprites && bug.sprites.happy);
    if (mine !== token) return;
    if (happy) await p.handle.setSprite(happy);
    if (mine !== token) return;
    // The same bug is now in two worlds (see reveal()); a greeting the child
    // cannot see because they happen to be holding the glass over it is not a
    // greeting, so the magnified copy changes frame too.
    if (happy && lens) lens.setSpriteUrl(bugId, happy);
    if (!scene.reducedMotion) p.handle.wiggle({ ms: T(Number(tuning.wiggleMs) || 420), deg: 6 });

    const isTarget = bugId === targetId;
    const detective = Boolean(ctx.modeDef() && ctx.modeDef().wrongTapRepeatsPrompt);

    if (isTarget) {
      // §3.5 — name → 140 → yes-N, then the spread opens. Bounded: nothing in
      // this game ever waits on audio, and a blocked clip must not strand the
      // child on a wiggling ladybug.
      const spoken = voice.seq(
        [bugVoice(bugId, 'name'), { key: ctx.yesKey(), gap: 140 }].filter((s) => s && (s.key || typeof s === 'string')),
        ctx.timeScale(),
      );
      await Promise.race([spoken, wait(T(2600))]);
      if (mine !== token) return;
      await wait(T(320));
      if (mine !== token) return;
      if (on.target) on.target(bugId);
      return;
    }

    wrongTaps += 1;
    const steps = [bugVoice(bugId, 'name'), { key: 'nudge-wrong', gap: 140 }];
    if (detective) steps.push({ key: bugVoice(targetId, 'clue'), gap: 300 });
    voice.seq(steps.filter((s) => s && (typeof s === 'string' || s.key)), ctx.timeScale());
    if (on.roommate) on.roommate(bugId, wrongTaps);

    // The happy frame is a greeting, not a verdict: it relaxes back to idle and
    // the bug stays tappable forever (§9.4).
    later(Number(tuning.happyHoldMs) || 900, async () => {
      if (mine !== token) return;
      const idle = await resolveArt(bug.sprites && bug.sprites.idle);
      if (mine !== token || !idle) return;
      p.handle.setSprite(idle);
      if (lens) lens.setSpriteUrl(bugId, idle);
    });
  }

  /**
   * §7.3 — THE single tap handler. `scene.onTap` and `QLOBE_DEBUG.tap()` both
   * land here; there is no test-only code path. Resolves when the resulting
   * choreography settles.
   */
  async function handleTap(id) {
    const key = String(id);
    if (view === 'hotel') {
      if (!roomById.has(key) || ctx.screen() !== 'hotel') return { accepted: false, role: 'none' };
      sfx.pop();
      if (on.room) on.room(key);
      return { accepted: true, role: 'room' };
    }
    if (view !== 'room' || ctx.screen() !== 'room') return { accepted: false, role: 'none' };
    if (!revealed.has(key)) return { accepted: false, role: 'none' };
    const role = key === targetId ? 'target' : 'bug';
    await greet(key);
    return { accepted: role === 'target', role };
  }

  scene.onTap((id) => { void handleTap(id); });

  // -- §2.4 the hotel --------------------------------------------------------

  async function showHotel() {
    token += 1;
    const mine = token;
    cancelTimers();
    scene.clear();
    placements = [];
    roomDef = null;
    targetId = null;
    revealed.clear();
    if (lens) { lens.setEnabled(false); lens.setVisible(false); }
    view = 'hotel';
    mounted = false;

    const url = await resolveArt((config.splash && config.splash.bg) || null);
    if (mine !== token) return false;
    if (url) await scene.setBackground(url, { ms: T(420) });
    if (mine !== token) return false;

    for (const room of config.rooms || []) {
      const handle = scene.addHotspot({
        ...roomBox(room),
        id: room.id,
        sprite: null,
        alt: room.title || room.id,
        z: 3,
      });
      if (!handle) continue;
      // The plaque IS the hotspot sprite (§8.1 row 3) — icon only, no words.
      resolveArt(room.plaque).then((src) => {
        if (mine === token && src) handle.setSprite(src);
      });
    }
    buildBadges();
    layout = scene.layoutHint();
    mounted = true;
    return true;
  }

  /** §2.4 — one pulse sweep across the four plaques, 120 ms apart. */
  function pulseRooms() {
    if (view !== 'hotel') return;
    const mine = token;
    (config.rooms || []).forEach((room, i) => {
      later(120 * i, () => {
        const handle = scene.get(room.id);
        if (mine === token && handle) handle.pulse({ ms: T(900), scale: 1.06 });
      });
    });
  }

  // -- §9.2 entering a room --------------------------------------------------

  async function enterRoom(roomId) {
    token += 1;
    const mine = token;
    cancelTimers();
    const room = roomById.get(String(roomId));
    if (!room) return false;

    view = 'room';
    mounted = false;
    roomDef = room;
    revealed.clear();
    wrongTaps = 0;
    firstRevealDone = false;
    lastCloserAt = -Infinity;
    fx.replaceChildren();
    scene.clear();

    const round = ctx.round();
    targetId = targetForRoom(room, round, Number(tuning.targetCycle) || 3);
    placements = placeBugs(room, {
      seed: ctx.seed(),
      mode: ctx.mode() || 'bug-hunt',
      round,
      placed: Number(tuning.placedPerRoom) || 3,
    });

    // ONE resolved URL feeds BOTH worlds. If the base plate and the magnified
    // duplicate ever disagreed, the glass would show a different picture from
    // the one under it — see js/art.js.
    plateUrl = await resolveArt(room.bg);
    if (mine !== token) return false;
    if (plateUrl) await scene.setBackground(plateUrl, { ms: T(420) });
    if (mine !== token) return false;

    // Base hotspots: created EMPTY and DISABLED. A bug exists only inside the
    // lens until it is found (§8.1 rows 8–9).
    for (const p of placements) {
      p.handle = scene.addHotspot({
        ...bugBox(p),
        id: p.bugId,
        sprite: null,
        enabled: false,
        alt: ' ',
        z: 3,
      });
    }

    await ensureLens();
    if (mine !== token) return false;
    if (plateUrl) lens.setBackground(plateUrl);

    const sprites = await Promise.all(placements.map(async (p) => {
      const bug = bugById.get(p.bugId);
      const box = bugBox(p);
      return {
        id: p.bugId,
        url: await resolveArt(bug && bug.sprites && bug.sprites.idle),
        x: box.x, y: box.y, w: box.w, h: box.h,
      };
    }));
    if (mine !== token) return false;
    lens.setSprites(sprites);
    lens.setDwell({
      ms: T(Number(lensCfg.dwellMs) || 600),
      radiusArt: Number(lensCfg.dwellRadiusArt) || 150,
    });
    lens.setVisible(true);
    lens.setEnabled(true);
    await lens.moveTo(
      Number(lensCfg.startArt && lensCfg.startArt.x) || artW / 2,
      Number(lensCfg.startArt && lensCfg.startArt.y) || artH / 2,
    );
    layout = scene.layoutHint();
    mounted = true;

    // §9.2 — one glint at 900 ms, so the child sees the glass is a thing that
    // moves. Reduced motion turns it into a resolved no-op inside the module.
    later(900, () => { if (mine === token && lens) lens.glint(); });
    return true;
  }

  /** Marks a room finished for the round; drives the hotel badge (§2.4). */
  function markRoomDone(roomId, bugId) {
    doneRooms.set(String(roomId), String(bugId));
  }

  function clearRoomsDone() {
    doneRooms.clear();
    if (view === 'hotel') buildBadges();
  }

  function clearRoom() {
    token += 1;
    cancelTimers();
    fx.replaceChildren();
    scene.clear();
    placements = [];
    roomDef = null;
    targetId = null;
    revealed.clear();
    view = 'none';
    mounted = false;
    if (lens) { lens.setEnabled(false); lens.setVisible(false); }
  }

  // -- QA surface ------------------------------------------------------------

  function targets() {
    if (view === 'hotel') {
      return scene.rects().map((r) => ({
        id: r.id, role: 'room', rect: { ...r.rect }, enabled: r.enabled, state: r.state,
      }));
    }
    if (view !== 'room') return [];
    return scene.rects().map((r) => ({
      id: r.id,
      role: r.id === targetId ? 'target' : 'bug',
      rect: { ...r.rect },
      enabled: r.enabled,
      state: r.state,
      revealed: revealed.has(r.id),
    }));
  }

  return {
    scene,
    get lens() { return lens; },
    get view() { return view; },
    /** True once the plate, the hotspots and (in a room) the lens are live. */
    get mounted() { return mounted; },
    get roomId() { return roomDef ? roomDef.id : null; },
    get roomDef() { return roomDef; },
    get targetId() { return targetId; },
    get revealed() { return [...revealed]; },
    get placements() { return placements.map(({ bugId, zone, artX, artY }) => ({ bugId, zone, artX, artY })); },
    get wrongTaps() { return wrongTaps; },
    get layout() { return layout; },
    get lastReflow() { return lastReflow; },
    get seenAnyRoom() { return seenAnyRoom; },
    markSeenRoom() { seenAnyRoom = true; },
    get roomsDone() { return new Map(doneRooms); },

    showHotel,
    pulseRooms,
    enterRoom,
    clearRoom,
    markRoomDone,
    clearRoomsDone,
    handleTap,
    reveal,
    targets,

    /** Every not-yet-revealed bug, in placement order. `winRound()` uses it. */
    unrevealed() {
      return placements.filter((p) => !revealed.has(p.bugId)).map((p) => p.bugId);
    },

    /** The art centre of a placed bug — QA moves the lens onto it. */
    artOf(bugId) {
      const p = placements.find((q) => q.bugId === String(bugId));
      return p ? { x: p.artX, y: p.artY } : null;
    },

    /** §7 `fastTimer` — the dwell lives in the module, so it is re-tuned here. */
    retuneDwell() {
      if (lens) {
        lens.setDwell({
          ms: T(Number(lensCfg.dwellMs) || 600),
          radiusArt: Number(lensCfg.dwellRadiusArt) || 150,
        });
      }
    },

    setEnabled(on_) {
      scene.setEnabled(on_);
      if (lens) lens.setEnabled(Boolean(on_) && view === 'room');
    },

    reflow() {
      scene.reflow();
      if (lens) lens.resync();
    },

    destroy() {
      clearRoom();
      if (offDwell) offDwell();
      if (offMove) offMove();
      if (lens) lens.destroy();
      lens = null;
      fx.remove();
      scene.destroy();
    },
  };
}
