export default {
  id: 'red-green-light',
  engine: 'coach-timer',
  title: 'Red Light, Green Light',
  splashEmoji: 'emoji:🚦',
  voice: {
    intro: 'Watch the light and listen.',
    praise: 'Great switching.',
    cheer: 'You stopped and went with your whole body!',
  },
  modes: [
    {
      id: 'classic',
      title: 'Classic',
      type: 'signal',
      rounds: 5,
      cheer: 'You listened and froze like a statue!',
      endTitle: 'Great Listening',
      endArt: 'emoji:🚦',
      againLabel: 'AGAIN',
      states: [
        {
          id: 'go',
          art: 'emoji:🟢',
          color: '#58a945',
          sfx: 'pop',
          say: 'Green light! Go go go!',
          durSec: [3, 8],
        },
        {
          id: 'stop',
          art: 'emoji:🔴',
          color: '#c9503a',
          sfx: 'boing',
          say: 'Red light! Freeze like a statue!',
          durSec: [2, 5],
        },
      ],
    },
    {
      id: 'silly',
      title: 'Silly Switch',
      type: 'signal',
      rounds: 5,
      cheer: 'You switched your body in silly ways!',
      endTitle: 'Silly Switch',
      endArt: 'emoji:🚦',
      againLabel: 'AGAIN',
      states: [
        {
          id: 'go',
          art: 'emoji:🟢',
          color: '#58a945',
          sfx: 'pop',
          say: 'Green light! Go go go!',
          durSec: [3, 8],
        },
        {
          id: 'wiggle',
          art: 'emoji:🟡',
          color: '#f4c53d',
          sfx: 'silly',
          say: 'Yellow light! Wiggle in place!',
          durSec: [2, 4],
        },
        {
          id: 'stop',
          art: 'emoji:🔴',
          color: '#c9503a',
          sfx: 'boing',
          say: 'Red light! Freeze like a statue!',
          durSec: [2, 5],
        },
      ],
    },
  ],
};
