export default {
  id: 'sound-basket',
  engine: 'sort-into-bins',
  title: 'Sound Basket',
  splashEmoji: '🧺',
  copy: {
    home: 'Home',
    replay: 'Hear it again',
    playAgain: 'Play Again',
  },
  voice: {
    intro: 'Listen for the first sound. Put the picture in its letter basket.',
    nudge: 'Almost. Listen to the first sound and try another basket.',
    roundCheer: 'These sounds are sorted!',
    cheer: 'Sound baskets full! You listened to the first sounds!',
    yums: [
      'Good listening!',
      'That starts with the same sound!',
      'First-sound finder!',
    ],
  },
  modes: [
    {
      id: 'two',
      title: 'Two Baskets',
      prompt: 'Sort each picture by its first sound: buh or suh.',
      rounds: 3,
      itemsPerRound: 4,
      bins: [
        { id: 'b', art: 'shared:letter-tiles/b.png', alt: 'letter b basket', say: 'buh, b basket' },
        { id: 's', art: 'shared:letter-tiles/s.png', alt: 'letter s basket', say: 'suh, s basket' },
      ],
      items: [
        { art: 'shared:objects/bat.webp', alt: 'bat', say: 'bat', bin: 'b' },
        { art: 'shared:objects/bag.webp', alt: 'bag', say: 'bag', bin: 'b' },
        { art: 'shared:objects/bed.webp', alt: 'bed', say: 'bed', bin: 'b' },
        { art: 'shared:objects/big.webp', alt: 'big', say: 'big', bin: 'b' },
        { art: 'shared:objects/bin.webp', alt: 'bin', say: 'bin', bin: 'b' },
        { art: 'shared:objects/bug.webp', alt: 'bug', say: 'bug', bin: 'b' },
        { art: 'shared:objects/bun.webp', alt: 'bun', say: 'bun', bin: 'b' },
        { art: 'shared:objects/bus.webp', alt: 'bus', say: 'bus', bin: 'b' },
        { art: 'shared:objects/sat.webp', alt: 'sat', say: 'sat', bin: 's' },
        { art: 'shared:objects/sad.webp', alt: 'sad', say: 'sad', bin: 's' },
        { art: 'shared:objects/sip.webp', alt: 'sip', say: 'sip', bin: 's' },
        { art: 'shared:objects/sit.webp', alt: 'sit', say: 'sit', bin: 's' },
        { art: 'shared:objects/six.webp', alt: 'six', say: 'six', bin: 's' },
        { art: 'shared:objects/sob.webp', alt: 'sob', say: 'sob', bin: 's' },
        { art: 'shared:objects/sun.webp', alt: 'sun', say: 'sun', bin: 's' },
        { art: 'shared:objects/sub.webp', alt: 'sub', say: 'sub', bin: 's' },
      ],
    },
    {
      id: 'three',
      title: 'Three Baskets',
      prompt: 'Sort each picture by its first sound: kuh, muh, or puh.',
      rounds: 3,
      itemsPerRound: 5,
      bins: [
        { id: 'c', art: 'shared:letter-tiles/c.png', alt: 'letter c basket', say: 'kuh, c basket' },
        { id: 'm', art: 'shared:letter-tiles/m.png', alt: 'letter m basket', say: 'muh, m basket' },
        { id: 'p', art: 'shared:letter-tiles/p.png', alt: 'letter p basket', say: 'puh, p basket' },
      ],
      items: [
        { art: 'shared:objects/cat.webp', alt: 'cat', say: 'cat', bin: 'c' },
        { art: 'shared:objects/can.webp', alt: 'can', say: 'can', bin: 'c' },
        { art: 'shared:objects/cap.webp', alt: 'cap', say: 'cap', bin: 'c' },
        { art: 'shared:objects/cog.webp', alt: 'cog', say: 'cog', bin: 'c' },
        { art: 'shared:objects/cup.webp', alt: 'cup', say: 'cup', bin: 'c' },
        { art: 'shared:objects/cut.webp', alt: 'cut', say: 'cut', bin: 'c' },
        { art: 'shared:objects/mat.webp', alt: 'mat', say: 'mat', bin: 'm' },
        { art: 'shared:objects/man.webp', alt: 'man', say: 'man', bin: 'm' },
        { art: 'shared:objects/map.webp', alt: 'map', say: 'map', bin: 'm' },
        { art: 'shared:objects/mop.webp', alt: 'mop', say: 'mop', bin: 'm' },
        { art: 'shared:objects/mug.webp', alt: 'mug', say: 'mug', bin: 'm' },
        { art: 'shared:objects/mud.webp', alt: 'mud', say: 'mud', bin: 'm' },
        { art: 'shared:objects/pan.webp', alt: 'pan', say: 'pan', bin: 'p' },
        { art: 'shared:objects/pad.webp', alt: 'pad', say: 'pad', bin: 'p' },
        { art: 'shared:objects/pen.webp', alt: 'pen', say: 'pen', bin: 'p' },
        { art: 'shared:objects/pig.webp', alt: 'pig', say: 'pig', bin: 'p' },
        { art: 'shared:objects/pot.webp', alt: 'pot', say: 'pot', bin: 'p' },
        { art: 'shared:objects/pug.webp', alt: 'pug', say: 'pug', bin: 'p' },
      ],
    },
  ],
};
